[package]
name = "implementations"
version = "0.1.0"
authors = ["edwinb-ai <developeredwin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ray-tracer = {path = "../lib"}